#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-python_dotenv
Version  : 0.21.0
Release  : 10
URL      : https://files.pythonhosted.org/packages/87/8d/ab7352188f605e3f663f34692b2ed7457da5985857e9e4c2335cd12fb3c9/python-dotenv-0.21.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/87/8d/ab7352188f605e3f663f34692b2ed7457da5985857e9e4c2335cd12fb3c9/python-dotenv-0.21.0.tar.gz
Summary  : Read key-value pairs from a .env file and set them as environment variables
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-python_dotenv-bin = %{version}-%{release}
Requires: pypi-python_dotenv-license = %{version}-%{release}
Requires: pypi-python_dotenv-python = %{version}-%{release}
Requires: pypi-python_dotenv-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(black)
BuildRequires : pypi(bumpversion)
BuildRequires : pypi(click)
BuildRequires : pypi(flake8)
BuildRequires : pypi(ipython)
BuildRequires : pypi(py)
BuildRequires : pypi(sh)
BuildRequires : pypi(tox)
BuildRequires : pypi(twine)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
# python-dotenv
[![Build Status][build_status_badge]][build_status_link]
[![PyPI version][pypi_badge]][pypi_link]

%package bin
Summary: bin components for the pypi-python_dotenv package.
Group: Binaries
Requires: pypi-python_dotenv-license = %{version}-%{release}

%description bin
bin components for the pypi-python_dotenv package.


%package license
Summary: license components for the pypi-python_dotenv package.
Group: Default

%description license
license components for the pypi-python_dotenv package.


%package python
Summary: python components for the pypi-python_dotenv package.
Group: Default
Requires: pypi-python_dotenv-python3 = %{version}-%{release}

%description python
python components for the pypi-python_dotenv package.


%package python3
Summary: python3 components for the pypi-python_dotenv package.
Group: Default
Requires: python3-core
Provides: pypi(python_dotenv)
Requires: pypi(black)
Requires: pypi(bumpversion)
Requires: pypi(click)
Requires: pypi(flake8)
Requires: pypi(ipython)
Requires: pypi(sh)
Requires: pypi(tox)
Requires: pypi(twine)
Requires: pypi(wheel)

%description python3
python3 components for the pypi-python_dotenv package.


%prep
%setup -q -n python-dotenv-0.21.0
cd %{_builddir}/python-dotenv-0.21.0
pushd ..
cp -a python-dotenv-0.21.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1666742937
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-python_dotenv
cp %{_builddir}/python-dotenv-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-python_dotenv/36fe354f4526001c781c4c99847c059ebc00878c || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dotenv

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-python_dotenv/36fe354f4526001c781c4c99847c059ebc00878c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
